version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-node-browsers # The primary container where steps are run
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: spacebankdb
          MYSQL_USER: root
          MYSQL_PASSWORD: admin1
   steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command:        
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root -admin1 spacebankdb < sql-data/dummy.sql
            mysql -h 127.0.0.1 -u root -admin1 --execute="CREATE DATABASE IF EXISTS spacebankdb "
workflows:
  version: 2
  build-deploy:
    jobs:
      - build          
orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
