# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build SpaceBank Spring Boot Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: spacebankdb
  pool: 5
  username: root
  password: admin1
  socket: /tmp/mysql.sock
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
