# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build SpaceBank Spring Boot Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses:  samin/mysql-action@v1.3
      name: Start Mysql
      with:
        host port: 3306 # optional, default is 3306
        container port: 3306 # optional, default is 3306
        character set server: utf8mb4 # optional, default is utf8mb4
        collation server: utf8mb4_general_ci # optional, default is utf8mb4_general_ci
        mysql version: '8.0'  # optional, default is latest
        mysql root password: root # optional, default is 
        mysql database: spacebankdb # optional, default is 
        mysql user: root # optional, default is 
        mysql password: admin # optional, default is 
      
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
